In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [43]:
N = 5
idx = np.arange(0, N)
x1 = torch.zeros(N,1)
x2 = torch.randn(N,1)
x3 = torch.cat([x1, x2], axis=1)
print(x1)
print(x2)
print(x3)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[-0.4037],
        [-0.4650],
        [ 1.0998],
        [-1.4181],
        [ 1.5328]])
tensor([[ 0.0000, -0.4037],
        [ 0.0000, -0.4650],
        [ 0.0000,  1.0998],
        [ 0.0000, -1.4181],
        [ 0.0000,  1.5328]])


In [50]:
noise = torch.randn(N,1)
y = x3 + noise
print(x3, x3.shape)
print(noise, noise.shape)
print(y)

tensor([[ 0.0000, -0.4037],
        [ 0.0000, -0.4650],
        [ 0.0000,  1.0998],
        [ 0.0000, -1.4181],
        [ 0.0000,  1.5328]]) torch.Size([5, 2])
tensor([[-0.7125],
        [-1.0025],
        [-0.0940],
        [ 1.1789],
        [-0.9137]]) torch.Size([5, 1])
tensor([[-0.7125, -1.1162],
        [-1.0025, -1.4675],
        [-0.0940,  1.0058],
        [ 1.1789, -0.2392],
        [-0.9137,  0.6190]])
